package com.pramodbharti.filmo.ui.theme

import androidx.compose.ui.graphics.Color

val filmoLightPrimary = Color(0xFF825500)
val filmoLightOnPrimary = Color(0xFFFFFFFF)
val filmoLightPrimaryContainer = Color(0xFFFFDDAE)
val filmoLightOnPrimaryContainer = Color(0xFF2A1800)
val filmoLightSecondary = Color(0xFF6F5B40)
val filmoLightOnSecondary = Color(0xFFFFFFFF)
val filmoLightSecondaryContainer = Color(0xFFFADEBC)
val filmoLightOnSecondaryContainer = Color(0xFF271904)
val filmoLightTertiary = Color(0xFF516440)
val filmoLightOnTertiary = Color(0xFFFFFFFF)
val filmoLightTertiaryContainer = Color(0xFFD3EABC)
val filmoLightOnTertiaryContainer = Color(0xFF102004)
val filmoLightError = Color(0xFFBA1B1B)
val filmoLightErrorContainer = Color(0xFFFFDAD4)
val filmoLightOnError = Color(0xFFFFFFFF)
val filmoLightOnErrorContainer = Color(0xFF410001)
val filmoLightBackground = Color(0xFFFCFCFC)
val filmoLightOnBackground = Color(0xFF1F1B16)
val filmoLightSurface = Color(0xFFFCFCFC)
val filmoLightOnSurface = Color(0xFF1F1B16)
val filmoLightSurfaceVariant = Color(0xFFF0E0CF)
val filmoLightOnSurfaceVariant = Color(0xFF4F4539)
val filmoLightOutline = Color(0xFF817567)
val filmoLightInverseOnSurface = Color(0xFFF9EFE6)
val filmoLightInverseSurface = Color(0xFF34302A)
val filmoLightPrimaryInverse = Color(0xFFFFB945)


val filmoDarkPrimary = Color(0xFFFFB945)
val filmoDarkOnPrimary = Color(0xFF452B00)
val filmoDarkPrimaryContainer = Color(0xFF624000)
val filmoDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val filmoDarkSecondary = Color(0xFFDDC3A2)
val filmoDarkOnSecondary = Color(0xFF3E2E16)
val filmoDarkSecondaryContainer = Color(0xFF56442B)
val filmoDarkOnSecondaryContainer = Color(0xFFFADEBC)
val filmoDarkTertiary = Color(0xFFB8CEA2)
val filmoDarkOnTertiary = Color(0xFF243516)
val filmoDarkTertiaryContainer = Color(0xFF3A4C2B)
val filmoDarkOnTertiaryContainer = Color(0xFFD3EABC)
val filmoDarkError = Color(0xFFFFB4A9)
val filmoDarkErrorContainer = Color(0xFF930006)
val filmoDarkOnError = Color(0xFF680003)
val filmoDarkOnErrorContainer = Color(0xFFFFDAD4)
val filmoDarkBackground = Color(0xFF1F1B16)
val filmoDarkOnBackground = Color(0xFFEAE1D9)
val filmoDarkSurface = Color(0xFF1F1B16)
val filmoDarkOnSurface = Color(0xFFEAE1D9)
val filmoDarkSurfaceVariant = Color(0xFF4F4539)
val filmoDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val filmoDarkOutline = Color(0xFF9C8F80)
val filmoDarkInverseOnSurface = Color(0xFF1F1B16)
val filmoDarkInverseSurface = Color(0xFFEAE1D9)
val filmoDarkPrimaryInverse = Color(0xFF825500)